### ISSUE TITLE
Problem explor() after updating Rstudio

### ISSUE THREAD

**Issue by juliendgros** [juba/explor#40] opened 2022-06-21 12:59 UTC
Hello, 
Since the update to the latest version of Rstudio (I don't know if it's the cause, but it's concomitant), when I launch the explor() function, the window opens as before, but when I close it, R behaves as if it was not closed (impossible to run an instruction) and then crashes. 
I'm on version 4.0.3 of R. 
Am I the only one to have this problem? 
Thank you very much,
Julien

**Comment by juba** [comment] 2022-06-21 13:20
Hi,

I can't reproduce the issue unfortunately (latest RStudio, R 4.2.0). Does the explor interface directly open in an RStudio window, or does it open first in the viewer pane ?

**Comment by juliendgros** [comment] 2022-06-21 15:10
Thank you. 
The explor interface directly open in a Rstudio windows, as it did before. 
I replaced Rstudio with version 2022.02.3, there is the same problem. The following messages appear in red in the console when I lauch explor() :

This version of bslib is designed to work with rmarkdown version 2.7 or higher. 
This Font Awesome icon ('file-image-o') does not exist:
* if providing a custom `html_dependency` these `name` checks can 
  be deactivated with `verify_fa = FALSE`
This Font Awesome icon ('file-image-o') does not exist:
* if providing a custom `html_dependency` these `name` checks can 
  be deactivated with `verify_fa = FALSE`
Le chargement a nécessité le package : shiny
Warning: le package ‘shiny’ a été compilé avec la version R 4.0.5

**Comment by juliendgros** [comment] 2022-06-21 16:37
After installing a slightly newer version of R (4.1) and updating the packages, the problem seems to be solved (there were conflicts between versions of the packages used by explor(), apparently). Thank you (and to Milan Bouchet-Valat for his live support).

**Comment by juba** [comment] 2022-06-21 16:38
You could try with the development version of `explor`, it should at least remove the Font awesome warnings, but I doubt it will solve the problem.

Otherwise maybe try to upgrade your R version if it is possible, at least to the latest R 4.0.x ?

**Comment by SamGG** [comment] 2022-06-21 16:58
No problem under R4.0.3. explor() opens a tab in my default web browser in my case, not the RStudio one. I noticed that when closing the explor tab, the shiny app is still running. I don't know if it's intended. Stopping the Shiny app in the console requires extra code IIRC, but that's overkill. I just pressed Esc key and the console is ready again. So, nothing unusual.
May be there is some discrepancies with RStudio Shiny pseudo web browser. I never use it. If you want to force the app to use the system default web browser, you should add options in the shiny call.
Replace https://github.com/juba/explor/blob/3c705b157357d02cbe6a26c8e7e28d0d26c09674/R/explor_multi_PCA.R#L345 by 
```
},

options = list(launch.browser = TRUE)
```
Great job. Thanks for this package.

**Closed as completed** 2022-08-22 09:55 UTC
