### ISSUE TITLE
PCA with Factomine R using ind.sup and quali.sup simultaneously

### ISSUE THREAD

**Issue by Bhavanight** [juba/explor#21] opened 2017-10-18 10:06 UTC
Hi everyone,

I'm getting and error while trying to use explor on a FactomineR PCA with both supplementary individuals and categorical supplementary variables. The FactomineR function PCA runs fine, the problem comes from the explor function. Here's the script : 

**
> ACP<-PCA(data,quali.sup=10:16,ind.sup=1:3) 
> explor(ACP) 
Error in `$<-.data.frame`(`*tmp*`, "varname", value = c("Cluster", "Cluster",  :    replacement has 231 rows, data has 223
>
**

What's weird is that is works with supplementary individuals only and with categorical supplementary variables only but not with both.

**
> ACP<-PCA(data[4:65,],quali.sup=10:16)
> explor(ACP)

Listening on http://127.0.0.1:6421
**

**
> ACP<-PCA(data[,1:9],ind.sup=1:3)
> explor(ACP)

Listening on http://127.0.0.1:6421
**

I'd be grateful to have your expertise on this one because I'm very confused. Thank you!

**Comment by juba** [comment] 2017-10-18 10:53
Surely you're using the latest version of explor ?

I can't reproduce the problem with the data I use for testing, so there should be something in your data that triggers the bug. Would there be a way for you to send me those data, if they are not too big or confidential ?

**Comment by Bhavanight** [comment] 2017-10-18 12:41
Thank you very much for responding so quickly, it would be really cool if I
could get this to work because it's the best visual representation I've
seen so far !

I downloaded explor yesterday from Rstudio which directly searches in CRAN
project online library, so I think it's the latest version? How can I be
sure?

I'm sending you a text file with fake data built from my original file (the
numbers have been changed but the general structure is the same). I tried
to run it and got the same error.

You need to use this command to get the file, or the PCA won't work (it's
so the name of the individuals are in the first column) :

data<-read.table(file=file.choose(), sep="\t", header=TRUE, row.names=1,
check.names=FALSE)



Source thermale	pH	T	Ca	Mg	Na	K	HCO3	SO4	Cl	Cluster	Distance_PDN	Loc	Secteur	Campagne__acquisition	X_UTM	Y_UTM
BR16	6.75	25.9	0.37	2.39	18.35	0.86	21.7	0.56	4	Sixieme	5000	Cilaos	La_Chapelle	Famin__2016_05	339500	7662200
BC	6.45	22.7	4.26	18	7.7	0.59	45.39	0.12	6	Sixieme	12000	Bras_Cabot	Takamaka	BRGM_78_SGN_467_GTH	354400	7665700
OLIV2	6.05	26	4.11	4.57	46.96	0.55	42.67	6	2	Sixieme	5000	Salazie	Piton_dAnchaing	BRGM_RP_51189_FR__2001	343700	7671300
AGS	108.6	351.66	112.5	58.16	27.5	1.66	242	68.5	0	Deuxieme	3000	Salazie	Grand_Sable	BRGM_RC_65104_FR__2015	341400	7669700
BACH	97.85	365.71	40.71	36.85	56.28	1.71	205.42	2	0	Quatrieme	3000	Salazie	Bras_du_Parc	BRGM_RC_65104_FR__2015	343400	7669200
BB	74	251.11	47.11	37.55	61.33	0.77	171.44	23.55	0.02	Quatrieme	5000	Cilaos	Benjoin	BRGM_RP_51189_FR__2001	341800	7660500
BE	78.75	280	45.12	26	23.87	0.87	164.87	0.75	0	Quatrieme	4000	Cilaos	La_Chapelle	BRGM_RP_52673_FR__2003	339700	7662600
BE2	100.5	220	4.87	3.12	15.25	0.37	32.62	0.87	0	Premier	2000	Cilaos	Bras_des_Etangs	BRGM_RP_35833_FR__1992	341100	7663300
BR1	4.37	10.81	2.09	1.03	4.24	0.06	10.08	0.05	0	Quatrieme	2000	Cilaos	Bras_Rouge_Amont	BRGM_RP_52673_FR__2003	340100	7664600
BR10	56.45	170	19.45	16.54	13.72	0.18	93.18	0.72	0	Premier	3000	Cilaos	Bras_Rouge	BRGM_RP_52673_FR__2003	339200	7663400
BR11	3.66	9.66	1.06	0.82	0.98	0.02	4.77	0.03	0	Premier	4000	Cilaos	Bras_Rouge	BRGM_RP_52673_FR__2003	339200	7663200
BR12	37.11	191.76	11.29	6.64	35.23	0.7	46.82	9.41	0.02	Troisieme	4000	Cilaos	Bras_Rouge	BRGM_RP_52673_FR__2003	339300	7663100
BR13	6.49	15.33	0.76	0.89	0.83	0.03	3.89	0.09	0	Premier	4000	Cilaos	La_Chapelle	BRGM_RP_52673_FR__2003	339600	7662800
BR14	6.51	37.42	1.59	1.35	11.16	0.25	11.94	2.13	0.04	Troisieme	4000	Cilaos	La_Chapelle	BRGM_RP_51189_FR__2001	339500	7662700
BR15	4.11	11.7	1.13	1.38	1.38	0.13	6.77	0.1	0	Quatrieme	4000	Cilaos	La_Chapelle	BRGM_RP_52673_FR__2003	339400	7662500
BR17	13	55	4.1	2.78	17.14	0.56	24.88	2.36	0.08	Troisieme	4000	Cilaos	La_Chapelle	BRGM_RP_52673_FR__2003	339500	7662100
BR18	17.02	47.91	2.75	1.91	6.25	0.12	12.45	2.02	0	Premier	4000	Cilaos	La_Chapelle	BRGM_RP_52673_FR__2003	339500	7662000
BR2	27.93	50	8.03	4.51	18.72	0.41	31.44	5.86	0	Premier	2000	Cilaos	Bras_Rouge_Amont	BRGM_RP_52673_FR__2003	340000	7664800
BR21	29.52	119.52	8.33	2.76	46.66	0.47	35.38	2.38	0.02	Troisieme	2000	Cilaos	Bras_Rouge_Amont	Famin__2016_08	340100	7665600
BR27	28.47	89.13	6.17	14.65	24.47	3	65.21	2.08	0	Quatrieme	3000	Cilaos	Bras_Rouge	BRGM_RP_35833_FR__1992	339200	7663500
BR3	12.93	48.57	6.24	2.69	5.85	0.18	24.28	0.59	0	Premier	2000	Cilaos	Bras_Rouge_Amont	BRGM_RP_52673_FR__2003	339900	7664500
BR4	9.45	22.95	4.61	1.95	1.9	0.11	14.69	0.29	0	Premier	2000	Cilaos	Bras_Rouge_Amont	BRGM_RP_52673_FR__2003	339700	7664500
BR5	30.65	96.52	11.39	4.95	20.82	0.43	50.04	1	0	Premier	2000	Cilaos	Bras_Rouge_Amont	BRGM_RP_52673_FR__2003	339700	7664500
BR6	41.53	147.33	18.86	5.66	18.13	0.4	59.6	3.26	0	Premier	2000	Cilaos	Bras_Rouge_Amont	BRGM_RP_52673_FR__2003	339700	7664300
BR7	16.02	45.38	8.89	2.17	4.25	0.12	21.1	1.82	0	Premier	3000	Cilaos	Bras_Rouge_Amont	BRGM_RP_52673_FR__2003	339500	7664100
BR8	57.41	195.83	19.16	9	10.16	0.5	66.33	1.91	0	Premier	3000	Cilaos	Bras_Rouge	BRGM_RP_52673_FR__2003	339200	7663600
BR9	77.62	327.5	29.37	23.5	28.75	1.25	134	1.87	0	Premier	3000	Cilaos	Bras_Rouge	BRGM_RP_52673_FR__2003	339200	7663500
DUP	73.63	211.81	12.63	11.36	25.27	0.72	65.72	3.54	0	Premier	3000	Salazie	Bras_du_Parc	BRGM_RC_65104_FR__2015	343700	7669600
EDN	91.57	364.28	45.28	88.14	57	3.14	328.57	1.71	0	Quatrieme	3000	Salazie	Riviere_du_Mat	BRGM_RC_65104_FR__2015	344400	7668600
FJ1	26.19	69.61	8.8	7.38	5.76	0.3	38.11	0.3	0	Premier	4000	Cilaos	Piton_de_Sucre	BRGM_RP_52673_FR__2003	339000	7662500
FJ2	66.1	200	36.4	25.7	32.5	1.5	146.7	1.1	0	Quatrieme	4000	Cilaos	Piton_de_Sucre	BRGM_RP_52673_FR__2003	338900	7662600
FJ3	64.5	196	10.6	10.7	3.4	0.2	48.3	0.7	0	Premier	4000	Cilaos	La_Chapelle	BRGM_RP_52673_FR__2003	339300	7662300
G1	57.5	140	29.33	15.08	41.58	1.5	119.58	2.16	0	Quatrieme	4000	Cilaos	Gobert	BRGM_RP_52673_FR__2003	338800	7663800
G2	2.06	4.49	0.84	0.78	0.81	0.03	4.12	0.02	0	Quatrieme	3000	Cilaos	Gobert	BRGM_RP_52673_FR__2003	339000	7663700
G3	0.83	2.52	0.38	0.3	0.29	0.01	1.7	0.01	0	Quatrieme	3000	Cilaos	Gobert	BRGM_RP_52673_FR__2003	339000	7663700
G4	10.7	37.24	5.29	4.2	6.39	0.25	23.58	0.2	0	Quatrieme	3000	Cilaos	Gobert	BRGM_RP_52673_FR__2003	339000	7663600
GDS	7.06	17.15	4.34	2.04	1.2	0.06	8.06	3.06	0	Deuxieme	3000	Salazie	Grand_Sable	BRGM_RC_65104_FR__2015	341400	7669800
HB1	51.07	158.57	7.14	12.92	9.28	0.78	49.78	0	0	Premier	5000	Salazie	Hell_Bourg	BRGM_78_SGN_467_GTH	346700	7669400
IMA	67	225	23.4	20	137	2.6	201.2	5.8	0.06	Troisieme	5000	Salazie	Piton_dAnchaing	BRGM_78_SGN_467_GTH	343800	7671000
IRN	199.33	1260	153.66	152.33	534.66	7	1040	36.33	0	Cinquieme	3000	Cilaos	Thermes	BRGM_RP_51189_FR__2001	341100	7662600
MAN	111.16	506.66	13.5	47.33	74.16	3.5	223.16	2.33	0	Quatrieme	2000	Salazie	Riviere_du_Mat_Amont	Famin__2016_07	344700	7667500
MAN G	9.4	22.61	4.75	3.61	3.21	0.13	18.8	0.11	0	Quatrieme	2000	Salazie	Riviere_du_Mat_Amont	BRGM_RP_51189_FR__2001	344700	7667500
MANa	13.74	33.11	0.95	1.13	1.35	0.31	2.68	0.06	0	Premier	1000	Salazie	Riviere_du_Mat_Amont	Famin__2016_07	343600	7666400
MANc	11.52	34.31	2.62	2.94	3.5	0.47	4.37	0.11	0	Premier	2000	Salazie	Riviere_du_Mat_Amont	Famin__2016_07	344000	7666600
MANECE	3.08	17.91	2.3	2.36	7.43	0.09	15.41	0.48	0	Cinquieme	3000	Cilaos	Thermes	BRGM_RP_51189_FR__2001	341400	7662800
MF1	94.2	160	1.1	0.1	35	0.2	2.6	4.5	0.14	Troisieme	8000	Mafate	Bronchard	BRGM_78_SGN_467_GTH	335100	7670400
OLIV1	5.62	14.65	1.06	0.99	4.37	0.08	6.35	0.39	0.09	Troisieme	5000	Salazie	Piton_dAnchaing	BRGM_RP_51189_FR__2001	344100	7671300
OLIVbis	94.87	232.5	28.62	17	22.87	0.62	68.87	21.62	0	Premier	5000	Salazie	Piton_dAnchaing	BRGM_RC_62181_FR__2013	343700	7671300
PC	72.7	216	11.6	11.5	5.7	1.5	50.3	1	0	Premier	7000	Salazie	Pente_Carozin	BRGM_RC_62181_FR__2013	343600	7673400
PISSA	24.66	68.14	16.44	5.22	11.51	0.14	42.81	4.77	0	Premier	2000	Cilaos	Bras_Rouge_Amont	BRGM_RP_51189_FR__2001	339800	7664300
RB1	3.52	11.71	0.6	1.08	0.71	0.11	4.66	0.04	0	Premier	3000	Salazie	Grand_Sable	Famin__2016_09	340800	7669700
RB2	1.23	4	0.22	0.39	0.25	0.03	1.98	0.02	0	Premier	3000	Salazie	Grand_Sable	Famin__2016_09	340900	7669800
RBR3	26.89	43.21	3.46	2.64	2.96	0.21	13.92	0.96	0	Premier	0	Cilaos	Rond_de_Bras_Rouge	Famin__2016_08	341300	7666200
RBR5	8.53	15.38	2.03	1.47	1.32	0.06	4.57	1.85	0	Premier	0	Cilaos	Rond_de_Bras_Rouge	Famin__2016_08	341200	7666200
RBR8	14.88	27	9.6	3.52	1.94	0.12	9.22	9.88	0	Deuxieme	1000	Cilaos	Rond_de_Bras_Rouge	Famin__2016_08	341000	7666100
RFOUQ	92.37	240	35.87	28.25	27.5	0.62	141.25	3.5	0	Premier	4000	Salazie	Riviere_du_Mat	BRGM_RP_51189_FR__2001	343300	7670600
RR1	2.23	11.77	0.2	0.51	3.73	0.1	2.67	0.32	0.09	Troisieme	5000	Cilaos	Ravine_Rouille	Famin__2016_05	338700	7661800
sRMAT	10.63	24.32	2.63	8.06	4.94	0.4	23.91	0.67	0	Quatrieme	5000	Salazie	Riviere_du_Mat	BRGM_RP_51189_FR__2001	344400	7671200
sRMAT2	7.26	21.85	1.95	1.46	1.95	0.07	8.41	0.08	0	Premier	4000	Salazie	Riviere_du_Mat	BRGM_RP_51189_FR__2001	343700	7670100
sRMAT3	184.75	652.5	87.25	70	239.25	4.75	389	69	0.01	Quatrieme	4000	Salazie	Riviere_du_Mat	BRGM_RP_51189_FR__2001	343600	7670100
TB	0.84	3.99	0.18	0.08	1.25	0.03	1.68	0.08	0.05	Troisieme	5000	Salazie	Riviere_du_Mat	BRGM_RC_62181_FR__2013	343900	7670800
TBA	9.08	38.55	5.79	3.56	10.24	0.23	24.56	1.4	0	Quatrieme	4000	Salazie	Riviere_du_Mat	BRGM_RC_65104_FR__2015	343700	7670100
TH HB bis	0.53	1.29	0	0	0.13	0	0.1	0	0	Premier	5000	Salazie	Hell_Bourg	BRGM_RC_62181_FR__2013	345700	7669700
TR	0.37	1.24	0.22	0.26	0.07	0	0.05	0.48	0	Deuxieme	8000	Salazie	Grand_ilet	BRGM_RC_62181_FR__2013	341900	7674700
VERO	0.31	1.78	0.21	0.21	0.63	0	1.38	0.04	0	Cinquieme	3000	Cilaos	Thermes	BRGM_RP_51189_FR__2001	341400	7662800

**Comment by juba** [comment] 2017-10-18 13:18
Thanks a lot for the data. The problem is identified, I should commit a fix in the afternoon.

It is caused by the fact that some levels of your supplementary variables are only present in your supplementary individuals. One way to quick fix it before I publish the commit could be, if I'm not wrong, to convert all your supplementary variables to factors (some of them are integers) before applying PCA.

Thanks again, I'll let you know when the problem is fixed.

**Comment by Bhavanight** [comment] 2017-10-18 13:29
Thank you so much! I'm pretty sure I wouldn't have found out on my own.

**Comment by juba** [comment] 2017-10-18 14:05
Ok, so I think the bug should be fixed in development version.

To install it, you have to install the `devtools` package and then do : 

    devtools::install_github("juba/explor")

Let me know if the problem is fixed for you.

And thanks for taking the time to report the bug and giving a reproducible example !

**Comment by Bhavanight** [comment] 2017-10-19 14:15
Works like a charm!

**Comment by juba** [comment] 2017-10-19 14:16
Great, thanks for letting me know.

**Closed as completed by juba** 2017-10-19 14:16 UTC
